# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-26 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
