# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-27 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201027_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
